### ISSUE TITLE
Słaby kod

### ISSUE THREAD

**Issue by iUnixPL** [TheEasyPeasy/SafeMC-AntiCheatPack-Auth#1]

**Comment by vocan** [comment]
❤️

**Comment by TheEasyPeasy** [comment]
@iUnixPL No ta przecieżto wasz kod to jaki miałby być

**Comment by iUnixPL** [comment]
Ale to u ciebie jest, to raczej twoje nazewnictwo.

**Comment by vocan** [comment]
masz racje, slaby
https://github.com/TheEasyPeasy/OrionPack-AntiCheatPack-Auth - to lepsze
:DDD

**Comment by iUnixPL** [comment]
TAK!!!!!!!!
